import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Menu } from "./menu";
import Image from "next/image";
import { WebSocketProvider } from "@/context/WebSocketContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <WebSocketProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <main className="relative h-screen bg-gray-100 dark:bg-gray-800 rounded-2xl">
            <div className="flex items-start">
              <div className="relative hidden h-screen my-4 ml-4 shadow-lg lg:block w-80">
                <div className="h-full bg-white rounded-2xl dark:bg-gray-700">
                  <div className="flex items-center justify-center pt-6">
                    <Image src="/ldr.png" alt={""} width={90} height={90} />
                  </div>
                  <Menu />
                </div>
              </div>
              <div className="flex flex-col w-full pl-0 md:p-4 md:space-y-4">
                <div className="h-screen pt-2 pb-24 pl-2 pr-2 overflow-auto md:pt-0 md:pr-0 md:pl-0">
                  {children}
                </div>
              </div>
            </div>
          </main>
        </body>
      </WebSocketProvider>
    </html>
  );
}
